# SAM/CloudFormation template for the incident notification system
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Incident Notification System

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 256
    CodeUri: ../src
    Tracing: Active
    Environment:
      Variables:
        INCIDENTS_TABLE_NAME: !Ref IncidentsTable
        INCIDENTS_TOPIC_ARN: !Ref IncidentNotificationsTopic

Resources:
  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Incidents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: incident_id
          AttributeType: S
      KeySchema:
        - AttributeName: incident_id
          KeyType: HASH

  IncidentNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: IncidentNotifications

  IncidentApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: IncidentApi
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PATCH,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,x-api-key'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Incident API usage plan
          Quota:
            Limit: 10000
            Period: MONTH
          Throttle:
            BurstLimit: 100
            RateLimit: 50

  CreateIncidentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-incident
      Handler: create_incident.handler.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IncidentApi
            Path: /incidents
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IncidentsTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt IncidentNotificationsTopic.TopicName

  GetIncidentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-incident
      Handler: get_incident.handler.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IncidentApi
            Path: /incidents/{id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref IncidentsTable

  ListIncidentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-incidents
      Handler: list_incidents.handler.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IncidentApi
            Path: /incidents
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref IncidentsTable

  UpdateIncidentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-incident
      Handler: update_incident.handler.lambda_handler
      Events:
        ApiEventPatch:
          Type: Api
          Properties:
            RestApiId: !Ref IncidentApi
            Path: /incidents/{id}
            Method: PATCH
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IncidentsTable

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: health-check
      Handler: health_check.handler.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IncidentApi
            Path: /health
            Method: GET

  IncidentApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: IncidentApiKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref IncidentApi
          StageName: prod

  IncidentUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: IncidentUsagePlan
      Description: Usage plan for Incident API
      ApiStages:
        - ApiId: !Ref IncidentApi
          Stage: prod
      Quota:
        Limit: 10000
        Period: MONTH
      Throttle:
        BurstLimit: 100
        RateLimit: 50

  IncidentUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref IncidentApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref IncidentUsagePlan

Outputs:
  ApiUrl:
    Description: Base URL for the Incident API
    Value: !Sub "https://${IncidentApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  IncidentsTableName:
    Description: Name of the incidents DynamoDB table
    Value: !Ref IncidentsTable

  IncidentNotificationsTopicArn:
    Description: ARN of the incident notifications SNS topic
    Value: !Ref IncidentNotificationsTopic